Repository milieuinfo/webcomponent-vl-ui-footer, pull requests merged in 2020-04, with the labels that each got.

#18 Introductie data-vl-development attribuut voor lokale ontwikkeling
  demo/vl-footer.html
  src/vl-footer.js
  test/unit/vl-footer.test.html
Labels: bug, enhancement

#20 Update vl-ui-util
  .mocharc.js
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
Labels: chore

#21 Update dependency @govflanders/vl-ui-util to v3.9.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate
